Dashboard wallet address display
Contrax-co/contrax-web pull request #11
Opened 2021-11-11 08:38 UTC by Huzaifa-Asif

- Get User Session by calling getUserSession() method, if session exists then parse the data to fetch wallet address and set the dataload variable to true
- Wallet Address Display on Navbar

2021-11-11 10:30 UTC, ShooterArk requested changes

2021-11-11 10:30 UTC, ShooterArk commented on src/components/Navigationbar.tsx
> +                        ) : (
remove line 46-48 and replace it with null, something like : null

2021-11-12 10:50 UTC, yawarshah1 approved these changes

2021-11-12 11:08 UTC, deenario commented on src/components/Banner.tsx
> +  dappId: 'b4ae356c-11d5-4439-baf0-8f452f2bdbcd',  // [String] The API key of Blocknative
@Huzaifa-Asif Shift these API Keys to an .env variable. Nothing should be static in the Project.

2021-11-12 11:23 UTC, merged