new design modals updated
Contrax-co/contrax-web pull request #51
Opened 2021-12-15 09:08 UTC by awaisdelta

2021-12-17 12:54 UTC, ShooterArk requested changes

2021-12-17 12:54 UTC, ShooterArk commented on src/components/button/Button.js
> +  size: 'lg',
please change it to 'large'

2021-12-17 12:54 UTC, ShooterArk commented on src/components/button/Button.styles.js
> +    border: 1px solid #63CCE0;
use color config file

2021-12-19 19:05 UTC, deenario approved these changes

2021-12-19 19:05 UTC, merged